name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: 
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to showcase repo"
        pr-message: "Pull successful :from showcase-admin"
